### ISSUE TITLE
not binding to device correctly (SO_BINDTODEVICE)

### ISSUE THREAD

**Issue by nihilus** [setaou/ndp-proxy#2]
One need to use a 'struct ifr' as argument to SO_BINDTODEVICE, there are some architectures where this matters (see the busybox source code for a proper implementation).

**Comment by mikma** [comment]
I checked the kernel source and I didn't find any reason to believe that 'struct ifreq' is required. Do you have a test case? The documentation in "man 7 socket" says "the passed option is a variable-length null-terminated interface name string with the maximum size of IFNAMSIZ".

**Comment by setaou** [comment]
Thanks for your contribution.
If I look at the Linux kernel source code for setsockopt(), in the case of SO_BINDTODEVICE, it leads to a call to sock_setbindtodevice(), which expect a char*. And looking at the code of that function it is used a string and not cast into anything else.
That is also what the manpage for setsockopt() says. I have no idea where the 'struct ifr' you mention comes from.
I see that @mikma has came to the same concusion with a perfect synchronization ;)

**Comment by setaou** [comment]
I am going to close the issue as this seems not to be a bug. You are still welcome to elaborate on the why and how that change should be made, and submit a pull request if you feel like it.
